{
 "title": "Dockerised Examples Dash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Virtual-Device2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"Virtual-Device2\")"
    }
   ]
  },
  {
   "title": "modbus-sim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"modbus-sim\")"
    }
   ]
  },
  {
   "title": "bacnet-ip-sim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"bacnet-ip-sim\")"
    }
   ]
  },
  {
   "title": "S7-Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"S7-Server\")"
    }
   ]
  }
 ]
}